ARG BUILD_FROM=python:3.12-slim
FROM $BUILD_FROM

# Install necessary packages
RUN pip install -r requirements.txt

# Copy your application files
COPY . /app
WORKDIR /app

# Make run.sh executable
RUN chmod a+x /app/run.sh
CMD [ "app/run.sh" ]

# Expose the port your application runs on
EXPOSE 5000